# cmake/GenGitInfo.cmake
#
# Runs git commands at build time and writes a C++ header with repo metadata.
# Invoked via add_custom_target() in CMakeLists.txt:
#
#   cmake -DSOURCE_DIR=<repo-root> -DOUTPUT_FILE=<path/git_info.h> -P GenGitInfo.cmake
#
# The header is regenerated on every build so the dirty flag is always current.

cmake_minimum_required(VERSION 3.15)

find_package(Git QUIET)

# ── Defaults (used when git is absent or the directory is not a repo) ─────────
set(GIT_COMMIT "unknown")
set(GIT_BRANCH "unknown")
set(GIT_DIRTY  false)

# ── Query the repository ───────────────────────────────────────────────────────
if(GIT_FOUND AND EXISTS "${SOURCE_DIR}/.git")

    # Short commit hash (8 hex chars)
    execute_process(
        COMMAND ${GIT_EXECUTABLE} -C "${SOURCE_DIR}" rev-parse --short=8 HEAD
        OUTPUT_VARIABLE GIT_COMMIT
        OUTPUT_STRIP_TRAILING_WHITESPACE
        ERROR_QUIET
        RESULT_VARIABLE _rc
    )
    if(NOT _rc EQUAL 0)
        set(GIT_COMMIT "unknown")
    endif()

    # Branch / tag / "HEAD" (detached)
    execute_process(
        COMMAND ${GIT_EXECUTABLE} -C "${SOURCE_DIR}" rev-parse --abbrev-ref HEAD
        OUTPUT_VARIABLE GIT_BRANCH
        OUTPUT_STRIP_TRAILING_WHITESPACE
        ERROR_QUIET
        RESULT_VARIABLE _rc
    )
    if(NOT _rc EQUAL 0)
        set(GIT_BRANCH "unknown")
    endif()

    # Dirty flag: any output from --porcelain means uncommitted changes exist
    execute_process(
        COMMAND ${GIT_EXECUTABLE} -C "${SOURCE_DIR}" status --porcelain
        OUTPUT_VARIABLE _status
        OUTPUT_STRIP_TRAILING_WHITESPACE
        ERROR_QUIET
    )
    if(NOT _status STREQUAL "")
        set(GIT_DIRTY true)
    endif()

endif()

# ── Write the header ───────────────────────────────────────────────────────────
get_filename_component(_dir "${OUTPUT_FILE}" DIRECTORY)
file(MAKE_DIRECTORY "${_dir}")

file(WRITE "${OUTPUT_FILE}" "\
// Auto-generated by cmake/GenGitInfo.cmake – do not edit.
// This file is regenerated on every build; it reflects the repo state at the
// time the linker ran, not at CMake configure time.
#pragma once

namespace git_info {

/// Short (8-char) SHA1 of the HEAD commit, or \"unknown\" if git is unavailable.
inline constexpr char kCommit[] = \"${GIT_COMMIT}\";

/// Branch name, tag, or \"HEAD\" in detached-head state; \"unknown\" as fallback.
inline constexpr char kBranch[] = \"${GIT_BRANCH}\";

/// True when the working tree had uncommitted changes at build time.
inline constexpr bool kDirty = ${GIT_DIRTY};

}  // namespace git_info
")

message(STATUS
    "git_info.h: commit=${GIT_COMMIT}  branch=${GIT_BRANCH}  dirty=${GIT_DIRTY}")
